// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
#pragma once

#include "CppSharp.h"
#include <Bar.h>

namespace Sample
{
    ref class Bar;
}

namespace Sample
{
    public ref class Bar : ICppInstance
    {
    public:

        property class ::Bar* NativePtr;
        property ::System::IntPtr __Instance
        {
            virtual ::System::IntPtr get();
            virtual void set(::System::IntPtr instance);
        }

        Bar(class ::Bar* native);
        Bar(class ::Bar* native, bool ownNativeInstance);
        static Bar^ __CreateInstance(::System::IntPtr native);
        static Bar^ __CreateInstance(::System::IntPtr native, bool __ownsNativeInstance);
        Bar();

        Bar(Sample::Bar^ _0);

        ~Bar();

        property int A
        {
            int get();
            void set(int);
        }

    protected:

        bool __ownsNativeInstance;
    };
}
